### ISSUE TITLE
More finegrained options for exporting only a specific subset of icons

### ISSUE THREAD

**Issue by nebulon42** [gmgeo/osmic#50]
New syntax:
```
input:
  - name: "administration"
    include:
      - "town-hall"
  - name: "amenity"
    include:
      - "cemetery"
      - "entrance-10"
      - "entrance-14"
  - name: "energy"
  - name: "outdoor"
    exclude:
      - "mast"
      - "waste-basket-14"
```
means:
of the directory administration only town-hall is included in the output, of the directory amenity cemetery and both sizes of entrance are included, everything within energy is included, of the directory outdoor everything but mast and the 14px version of waste-basket is included

include and exclude may never be specified together for one directory, in this case the directory is skipped.
